#pragma config(Sensor, in1,    CatapultPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in2,    FlipperPotentiometer, sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftLift,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightLift,      sensorQuadEncoder)
#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           backRightMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftCatapult,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightCatapult, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Flipper,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           BallBoy,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          backLeftMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void controllerdrive()
{
	//Right side of the robot is controlled by the right joystick, Y-axis
	motor[frontRightMotor] = vexRT[Ch2];
	motor[backRightMotor]  = vexRT[Ch2];
	//Left side of the robot is controlled by the left joystick, Y-axis
	motor[frontLeftMotor] = vexRT[Ch3];
	motor[backLeftMotor]  = vexRT[Ch3];
}

void liftcontrol()
{
	//Creates an integer LiftCtl that changes when the different buttons are pushed
	int LiftCtl = (vexRT[Btn6D] << 1) + vexRT[Btn6U];
	switch( LiftCtl )
   {
 	 	case 1://Btn6U is pressed making the lift go up
      motor[leftLift] = 127;
      motor[rightLift] = 127;
    break;

   	case 2://Btn6D is pressed making the lift go down
      motor[leftLift] = -127;
      motor[rightLift] = -127;
    break;

   	default://When both or neither button pressed lift is off
      motor[rightLift] = 0;
      motor[leftLift] = 0;
    break;
   }
}


void intakecontrol()
{

	//Btn8D turns intake on going in
	if(vexRT[Btn8D] == 1)
	{
		motor[BallBoy] = 127;
	}

	//Btn8L turns intake on going out
	if(vexRT[Btn8L] == 1)
	{
		motor[BallBoy] = -127;
	}

	//Btn8U turns intake off
	if(vexRT[Btn8U] == 1)
	{
		motor[BallBoy] = 0;
	}

}

void RotateRight(int potentiometeroutput)
{
	//If the cap is on the right side flip the cap to the left
	while(SensorValue[potentiometeroutput] < 2300)
	{
		motor[Flipper] = 35;
	}
	//Counter the inertia from the cap being flipper
	motor[Flipper] = 10;
	wait(200);
}

void RotateLeft(int potentiometeroutput)
{
	//If the cap is on the left side flip the cap to the right
	while(SensorValue[potentiometeroutput] > 100)
	{
		motor[Flipper] = -35;
	}
	//Counter the inertia from the cap being flipped
	motor[Flipper] = -10;
	wait(200);
}

int capflip(int FlippyDo)
{
	//If Btn5U pressed check the position of the cap flipper
	if(vexRT[Btn5U] == 1)
	{
		//If the cap flipper is to the right turn it to the left
		if(FlippyDo == 0)
		{
			RotateRight(FlipperPotentiometer);
			motor[Flipper] = 0;
			FlippyDo = 1;	//Note that the cap is now on the left
		}

		//If the cap flipper is to the left turn it to the right
		else if (FlippyDo == 1)
		{
			RotateLeft(FlipperPotentiometer);
			motor[Flipper] = 0;
			FlippyDo = 0; //Note that the cap is now on the right
		}
	}
return FlippyDo; //Send integer FlippyDo back to the taskmain to be reset
}

void catapultarm(int potentiometeroutput)
//Checks the value of the potentiometer to be put into the task
{
	//If catapult is not cocked start motors
	if(SensorValue[potentiometeroutput] > 1750)
	{
		motor[leftCatapult] = 127;
		motor[rightCatapult] = 127;
	}
	//If catapult is cocked stop motors
	else
	{
		motor[leftCatapult] = 0;
		motor[rightCatapult] = 0;
 	}
}

void catapultfire()
{
	//Btn8R turns the catapult on for a short period to fire
	if(vexRT[Btn8R] == 1)
	{
		motor[leftCatapult] = 127;
		motor[rightCatapult] = 127;

		wait1Msec(2);
	}

}

task main()
{
	//Declare integers used in the program
	int FlippyDo = 0;

	while(1 == 1)
	{

		//Drive program listed above
		controllerdrive();

		//Intake control listed above
		intakecontrol();

		//Lift control listed above
		liftcontrol();

		//The integer for FlippyDo gets sent back to the void to reevaluate itself for the orientation of the cap
		FlippyDo = capflip( FlippyDo );

		//Catapult fire program above
		catapultfire();

		//Catapult program listed above
		catapultarm(CatapultPotentiometer);

	}
}
