#pragma config(Sensor, in1,    CatapultPotentiometer, sensorPotentiometer)
#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           backRightMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftCatapult,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,          rightCatapult, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           BallBoy,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           backLeftMotor, tmotorVex393_Hbridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void controllerdrive()
{
	//Right side of the robot is controlled by the right joystick, Y-axis
	motor[frontRightMotor] = vexRT[Ch2];
	motor[backRightMotor]  = vexRT[Ch2];
	//Left side of the robot is controlled by the left joystick, Y-axis
	motor[frontLeftMotor] = vexRT[Ch3];
	motor[backLeftMotor]  = vexRT[Ch3];
}

void intakecontrol()
{
	//Btn8D turns on intake
	if(vexRT[Btn8D]==1)
	{
		motor[BallBoy]=-127;
	}

	//Btn8L turns off intake
	if(vexRT[Btn8L]==1)
	{
		motor[BallBoy]=0;
	}
}

void catapultarm(int potentiometeroutput)
{
	//If catapult is not cocked start motors
	if(SensorValue[potentiometeroutput] >1750)
	{
		motor[leftCatapult]=127;
		motor[rightCatapult]=127;
	}
	//If catapult is cocked stop motors
	else
	{
		motor[leftCatapult]=0;
		motor[rightCatapult]=0;
 	}
}

void catapultfire()
{
	//If Butn 8R Pressed Catapult Runs
	if(vexRT[Btn8R] == 1)
	{
		motor[leftCatapult]=127;
		motor[rightCatapult]=127;
	}

	//If Btn8R not pressed catapult doesnt move
	else
	{
		motor[leftCatapult]=0;
		motor[rightCatapult]=0;
	}
}

task main()
{
	while(1 == 1)
	{

		//Drive program listed above
		controllerdrive();

		//Intake control listed above
		intakecontrol();

		//Catapult fire program above
		catapultfire();

		//Catapult program listed above
		catapultarm(CatapultPotentiometer);

	}
}
